feat: add drizzle database connection as middleware
radicalplatforms/shafa pull request #32
Opened 2024-02-04 22:54 UTC by vincentdo1

2024-02-05 02:32 UTC, vincentdo1 commented on hono/src/service/items.ts
> +    .get('db')
Yes, c.get('db') gets a database that has already been instantiated.

2024-02-05 05:50 UTC, rak3rman commented on hono/src/service/items.ts
> +    .get('db')
I also verified behavior, that's an interesting and kinda cool feature.

2024-02-05 19:26 UTC, vincentdo1 commented on hono/src/service/items.ts
> +    await c.get('db').query.items.findMany({
I have tried specifying the return type for `c.get` function as suggested in the link but I still got typing errors. The only solution I was able to come up with was specifying type `c` to be `Context` but it seems other typing errors occur that I was not able to find a clean solution for. Let me know what you think.

2024-02-05 20:12 UTC, rak3rman commented on hono/src/service/items.ts
> +    await c.get('db').query.items.findMany({
Let me take a stab at it.

2024-02-06 19:03 UTC, rak3rman requested changes

2024-02-06 19:03 UTC, rak3rman commented on hono/src/service/items.ts
> +  const db = createDB(c)
This shouldn't be here :(

2024-02-06 19:06 UTC, rak3rman commented on hono/src/service/items.ts
> +    await c.get('db').query.items.findMany({
Marking as resolved, going to open another ticket for weak warnings that are appearing.

2024-02-06 19:06 UTC, rak3rman approved these changes

2024-02-06 19:15 UTC, SengdowJones approved these changes
LGTM!👍

2024-02-06 19:21 UTC, merged